baseURL = 'https://bckn.be/'
languageCode = 'nl-BE'
title = 'BCKN'
theme = "hugo-theme-anubis2"
enableEmoji = true

[params.author]
name = "Stefan"
email  = "stefan@bckn.be"
location = "Belgium"

[params]
toc = false
social = [
	{ id = "github", url = "https://github.com/stefanbckn" },
	{ id = "linkedin", url = "https://www.linkedin.com/in/stefanbocken" },
	{ id = "bluesky", url = "https://bsky.app/profile/stefanbckn.bsky.social" },
	{ id = "mastodon", url = "https://mastodon.social/@stefanbckn" }
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 5

[[menu.main]]
name = "Curriculum Vitae"
identifier = "cv"
url = "https://stefan.bckn.be"
weight = 6

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/

[params.SplitbeeAnalytics]
enabled = true

[outputs]
home = ['html', 'rss', 'notes']

[OutputFormats.notes]
	mediaType = "application/rss+xml"
	basename = "notes"